---
title: "Data Wrangling Final"
author: Chris Perry
format: gfm
execute: 
  warning: false
  message: false
  errors: false
jupyter: python3
---


Read in the data:
```{python}
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import seaborn as sns

batting = pd.read_csv("/Users/chrisperry/Downloads/Batting.csv")
people = pd.read_csv("/Users/chrisperry/Downloads/People.csv")
salary = pd.read_csv("/Users/chrisperry/Downloads/Salaries.csv")
```

merge data:
```{python}
merge1 = pd.merge(batting, people, how='left', left_on='playerID', right_on='playerID')
merge2 = pd.merge(merge1, salary, how='left', left_on='playerID', right_on='playerID')
merge2.columns
merge2.head
```

Filter merged data by last 5 years to view up-to-date stats:
```{python}
five = merge2[merge2['yearID_x'] >= merge2['yearID_x'].max() - 4]
five.head
```

Filter by minimum at bats to provide accurate results
```{python}
f_ab = five[five['AB'] >= 100].copy()
f_ab.head
```

Create an advanced statistic: OBP - on base percentage
```{python}
f_ab['OBP'] = (
    (f_ab['H'] + f_ab['BB'] + f_ab['HBP']) / 
    (f_ab['AB'] + f_ab['BB'] + f_ab['HBP'] + f_ab['SF'])
)

f_ab.columns
```


Visualize OBP and Salary as a scatterplot. Is there a visual relationship?

```{python}
sns.relplot(data = f_ab, x = 'salary', y ='OBP')
plt.show()
```

There appears to be little to no correlation between salary and obp

How many players have a salary over 3650000 and an OBP over 0.35?
```{python}
over365 = f_ab[(f_ab['salary']> 3650000) & (f_ab['OBP'] > 0.35)]

over365
```

There are 126 rows available providing records of this instance. Joey Votto and Jose Abreu were two players in 2020 and 2021 that had a salary of over 3650000 and an OBP of over 0.35

Is there a strong correlation between the number of at bats and on base percentage?

```{python}
sns.relplot(data = f_ab, x = 'AB', y ='OBP')
plt.show()
```

There is a stronger correlation here between AB and OBP compared to salary. This makes sense as likely the more at bats for a player the better chance they have to raise their OBP

Is there a strong correlation between RBIs and OBP?

```{python}
sns.relplot(data = f_ab, x = 'RBI', y ='OBP')
plt.show()
```

The correlation between RBI's and OBP appears to be positive just as AB's and OBP. RBI's do not necessarily correlate to OBP as a player can record an RBI and still be out on the play, but there are many scenarios(double - leads to a run score) that a player gets on base and scores runs in the process.

What is the correlation between OBP and multiple variables: HR, H, BB, HBP, RBI, AB, games batting, and salary? Which variables have the highest correlation?

```{python}
fit = smf.ols(formula='OBP ~ HR + H + BB + HBP + RBI + AB + G_batting + salary', data = f_ab).fit()
fit.summary()
```

There are enough variables contained in this regression to display a positive correlation. It is important to note the multicollinearity that occurs here as stats like Hits, BB, HBP, and AB all are included in the OBP formula. However, the goal was to research which stats impacted OBP more than others, even those included within the OBP formula. 
